services:
#    annonce.example:
#        class: AnnonceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    acme_hello.upload_listener:
        class: AnnonceBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
