# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        cm_userbundle:
            entity:
                class: UserBundle:User

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: cm_userbundle
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
                check_path: /login_check
                # the user is redir
                login_path: /connexion
                default_target_path: /mon-profile
                remember_me: true
                # csrf token options
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY} #requires_channel: https
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY } #requires_channel: https
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY } #requires_channel: https
        - { path: ^/admin/, role: ROLE_ADMIN }