# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    acme_hello.upload_listener:
        class: AnnonceBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload  }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    annoncebundle.locale_listener:
        class: AnnonceBundle\EventListener\LocalListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

#    local_listener:
#        class: AnnonceBundle\EventSubscriber\LocaleSubscriber:
#        arguments: ['%kernel.default_locale%']
#        # redundant if you're using autoconfigure
#        tags:
#            - { name: kernel.event_subscriber }
