<?php

namespace AnnonceBundle\Repository;

/**
 * AnonymeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnonymeRepository extends \Doctrine\ORM\EntityRepository
{
}
