<?php

namespace AnnonceBundle\Repository;

/**
 * categorieAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
