<?php

namespace AnnonceBundle\Repository;

/**
 * packageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class packageRepository extends \Doctrine\ORM\EntityRepository
{
}
