<?php

namespace AnnonceBundle\Repository;

/**
 * profilAnnonceurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class profilAnnonceurRepository extends \Doctrine\ORM\EntityRepository
{
}
