<?php

namespace AnnonceBundle\Repository;

/**
 * sousCategorieAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sousCategorieAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
