<?php

namespace AnnonceBundle\Repository;

/**
 * statutAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statutAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
