<?php

namespace AnnonceBundle\Repository;

/**
 * villeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class villeRepository extends \Doctrine\ORM\EntityRepository
{
}
